set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_C_COMPILER $ENV{BUILD_PREFIX}/bin/clang-cl)
set(CMAKE_CXX_COMPILER $ENV{BUILD_PREFIX}/bin/clang-cl)
set(CMAKE_AR $ENV{BUILD_PREFIX}/bin/llvm-lib)
set(CMAKE_LINKER $ENV{BUILD_PREFIX}/bin/lld-link)

set(LINK_FLAGS "/manifest:no")

set(CMAKE_EXE_LINKER_FLAGS "${LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${LINK_FLAGS}" CACHE STRING "" FORCE)