conda_forge_output_validation: true
provider:
  linux_64: azure
  linux_armv7l: azure
  osx_64: None
  win_64: None
  linux_ppc64le: None
  linux_aarch64: None
build_platform:
  linux_armv7l: linux_armv7l
  # osx_arm64: osx_64
  # linux_ppc64le: linux_64
  # linux_aarch64: linux_64
test: native
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
channels:
  sources:
    - e8035669acarmv7
    - conda-forge
  targets:
    - ['e8035669acarmv7', 'main']
channel_priority: flexible
remote_ci_setup: "e8035669acarmv7::conda-forge-ci-setup=3"
