MACOSX_DEPLOYMENT_TARGET:
- '0'
MACOSX_SDK_VERSION:
- '0'
cdt_name:
- cos7
cdt_arch:
- armv7l
channel_sources:
- conda-forge
channel_targets:
- conda-forge main
cross_target_platform:
- linux-armv7l
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
rust_arch:
- armv7-unknown-linux-gnueabihf
rust_arch_env:
- ARMV7_UNKNOWN_LINUX_GNUEABIHF
rust_arch_env_build:
- ARMV7_UNKNOWN_LINUX_GNUEABIHF
rust_default_cc:
- armv7l-conda-linux-gnueabihf-cc
rust_default_cc_build:
- armv7l-conda-linux-gnueabihf-cc
target_c_stdlib_version:
- '2.17'
target_platform:
- linux-armv7l
version:
- 1.79.0
zip_keys:
- - cross_target_platform
  - rust_arch
  - rust_arch_env
  - rust_default_cc
  - MACOSX_SDK_VERSION
  - MACOSX_DEPLOYMENT_TARGET
  - target_c_stdlib_version
  - channel_sources
  - channel_targets
  - version
BUILD:
- armv7-conda_cos7-linux-gnueabihf
